/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.utfpr.proj.projespjava;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cazevedo
 */
public class Cadastro extends javax.swing.JFrame {
    
    private RepositoryPessoa repository = new RepositoryPessoa();
    private Pessoa pessoa = new Pessoa();
    private static Cadastro cadastroPessoa;
    
    /**
     * Creates new form Cadastro
     */
    private Cadastro() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txfCPF = new javax.swing.JTextField();
        txfNome = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        scrTabelaPessoa = new javax.swing.JScrollPane();
        tabPessoa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblCPF.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblCPF.setText("CPF:");

        txfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCPFActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tabPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPessoaMouseClicked(evt);
            }
        });
        scrTabelaPessoa.setViewportView(tabPessoa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(btnSair))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(scrTabelaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNome)
                                .addComponent(lblCPF))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnInserir)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPesquisar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAlterar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnExcluir))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNome)
                                    .addComponent(txfCPF))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(33, 33, 33)
                .addComponent(scrTabelaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSair)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCPFActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        sair();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        inserirPessoa();
        atualizaTabela();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        consultaPessoa();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarPessoa();
        atualizaTabela();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirPessoa();
        atualizaTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPessoaMouseClicked
        selecionaPessoa();
    }//GEN-LAST:event_tabPessoaMouseClicked

    public void atualizaTabela(){
        // Recupera o objeto TableModel da tabela para que possamos trabalhar os dados
        DefaultTableModel modelo = (DefaultTableModel) tabPessoa.getModel();
        
        int posicaoLinha = 0;
        modelo.setRowCount(posicaoLinha);
        
        for (Pessoa p : repository.getBd()) {
            modelo.insertRow(posicaoLinha, new Object[]{ p.getCpf(), p.getNome() });
            posicaoLinha++;
        }
    }
    
    public void limpar() {
        txfCPF.setText("");
        txfNome.setText("");
        txfCPF.requestFocus();
    }
    
    public void sair() {
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "saida", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (resposta == 0) {
            dispose();
        }
    }
    
    public void inserirPessoa() {
        pessoa = new Pessoa();
        pessoa.setCpf(Integer.parseInt(txfCPF.getText()));
        pessoa.setNome(txfNome.getText());
        
        pessoa = repository.cadastrar(pessoa);
        if (pessoa != null) {
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!", "Sucesso", JOptionPane.OK_OPTION);
            limpar();
        } else {
            JOptionPane.showMessageDialog(null, "Pessoa já cadastrada!", "Erro", JOptionPane.ERROR_MESSAGE);
            txfCPF.requestFocus();
        }
    }
    
    public void consultaPessoa() {
        pessoa = new Pessoa();
        pessoa.setCpf(Integer.parseInt(txfCPF.getText()));
        
        pessoa = repository.pesquisar(pessoa);
        
        if(pessoa != null) {
            txfCPF.setText(Integer.toString(pessoa.getCpf()));
            txfNome.setText(pessoa.getNome());
            JOptionPane.showMessageDialog(null, "Cadastrado encontrado!", "Sucesso", JOptionPane.OK_OPTION);
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            txfCPF.requestFocus();
        }
    }
    
    public void alterarPessoa() {
        pessoa = new Pessoa();
        pessoa.setCpf(Integer.parseInt(txfCPF.getText()));
        
        pessoa = repository.atualizar(pessoa);
        
        if(pessoa != null) {
            txfCPF.setText(Integer.toString(pessoa.getCpf()));
            txfNome.setText(pessoa.getNome());
            limpar();
            JOptionPane.showMessageDialog(null, "Cadastrado alterado!", "Sucesso", JOptionPane.OK_OPTION);
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            txfCPF.requestFocus();
        }
    }
    
    public void excluirPessoa() {
        pessoa = new Pessoa();
        pessoa.setCpf(Integer.parseInt(txfCPF.getText()));
        
        pessoa = repository.remover(pessoa);
        
        if(pessoa == null) {
            limpar();
            JOptionPane.showMessageDialog(null, "Cadastrado excluído!", "Sucesso", JOptionPane.OK_OPTION);
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            txfCPF.requestFocus();
        }
    }
    
    public void selecionaPessoa() {
        String saida = "";
        
        int posicaoLinha = tabPessoa.getSelectedRow();
        
        for (int coluna = 0; coluna < tabPessoa.getColumnCount(); coluna++) {
            saida += tabPessoa.getModel().getValueAt(posicaoLinha, coluna).toString();
            
            if (coluna + 1 < tabPessoa.getColumnCount()) {
                saida += "\n";
            }
        }
        
        JOptionPane.showMessageDialog(null, "Dados: \n" + saida, "Dados Pessoa", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public static Cadastro criaCadastro(){
        if (cadastroPessoa == null) {
            cadastroPessoa = new Cadastro();
        }
        return cadastroPessoa;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNome;
    private javax.swing.JScrollPane scrTabelaPessoa;
    private javax.swing.JTable tabPessoa;
    private javax.swing.JTextField txfCPF;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
